// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7S6MPC-dmQ5LdPQYwsudq8LFy4dyf2iQ',
    appId: '1:957089684105:web:108cd8b0be75a956ee0458',
    messagingSenderId: '957089684105',
    projectId: 'gamemate-mobile',
    authDomain: 'gamemate-mobile.firebaseapp.com',
    storageBucket: 'gamemate-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEO41ciHIQb5pMquuc6WAvSoxVhKGzzuk',
    appId: '1:957089684105:android:416b5a0dc5bf91fcee0458',
    messagingSenderId: '957089684105',
    projectId: 'gamemate-mobile',
    storageBucket: 'gamemate-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8wFgOpgi_sJ6wBo2DPrkDrrbsS5EVSZE',
    appId: '1:957089684105:ios:e97d52a984f789ceee0458',
    messagingSenderId: '957089684105',
    projectId: 'gamemate-mobile',
    storageBucket: 'gamemate-mobile.appspot.com',
    iosBundleId: 'com.example.gamemateMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8wFgOpgi_sJ6wBo2DPrkDrrbsS5EVSZE',
    appId: '1:957089684105:ios:d7e62f9460ac02d7ee0458',
    messagingSenderId: '957089684105',
    projectId: 'gamemate-mobile',
    storageBucket: 'gamemate-mobile.appspot.com',
    iosBundleId: 'com.example.gamemateMobile.RunnerTests',
  );
}
